export default {
  "id": 39,
  "title": "Fake Reviews/Testimonials",
  "emoji": "⭐",
  "description": "When the 'people' aren't real.",
  "introduction": "Learn to recognize and protect yourself from Fake Reviews/Testimonials.",
  "warning_signs": [],
  "what_to_do": [],
  "how_it_works": "",
  "questions": [
    {
      "type": 1,
      "prompt": "A product has 5,000 reviews, all 5 stars, posted in the last 3 days.",
      "options": [
        "Popular product",
        "Bot attack. Natural reviews accumulate over time.",
        "Viral",
        "Good marketing"
      ],
      "correct": 1,
      "explanation": "A sudden spike in perfect reviews is the clearest sign of a bought bot campaign."
    },
    {
      "type": 1,
      "prompt": "The reviews use generic phrases like 'Good item', 'Fast ship', 'Nice'.",
      "options": [
        "Succinct",
        "Bot filler text. Real humans describe specific features.",
        "Lazy",
        "Efficient"
      ],
      "correct": 1,
      "explanation": "Bots use vague language that could apply to any product."
    },
    {
      "type": 1,
      "prompt": "The user names are random letters/numbers (e.g., 'User129384').",
      "options": [
        "Privacy",
        "Bot accounts generated by scripts.",
        "New",
        "Standard"
      ],
      "correct": 1,
      "explanation": "Real users usually have names or customizable handles."
    },
    {
      "type": 1,
      "prompt": "The review mentions a different product (e.g., review for headphones on a toaster page).",
      "options": [
        "Glitch",
        "Review Hijacking. The seller swapped the product page to keep old 5-star ratings.",
        "Mistake",
        "Confusion"
      ],
      "correct": 1,
      "explanation": "Sellers reuse old pages with high ratings for new junk products."
    },
    {
      "type": 1,
      "prompt": "A graph of reviews shows only 5-star and 1-star ratings (C-shape).",
      "options": [
        "Polarizing product",
        "Manipulation. Paid 5-stars vs Real angry 1-stars.",
        "Okay",
        "Normal"
      ],
      "correct": 1,
      "explanation": "Real products usually have a bell curve (mostly 3-4 stars)."
    },
    {
      "type": 1,
      "prompt": "The English is broken or unnatural across hundreds of reviews.",
      "options": [
        "Global buyers",
        "Click farm content.",
        "Translation",
        "Fine"
      ],
      "correct": 1,
      "explanation": "Click farms often use poor translation software."
    },
    {
      "type": 1,
      "prompt": "All the reviewers have only reviewed this one single item.",
      "options": [
        "Loyal",
        "Fake accounts created solely for this scam.",
        "New",
        "Fan"
      ],
      "correct": 1,
      "explanation": "Real shoppers have a history of diverse purchases."
    },
    {
      "type": 1,
      "prompt": "Can you trust 'Amazon's Choice' blindly?",
      "options": [
        "Yes",
        "No, it's an algorithm based on sales volume (which can be faked)",
        "Always",
        "Maybe"
      ],
      "correct": 1,
      "explanation": "The badge is algorithmic, not a quality guarantee."
    },
    {
      "type": 1,
      "prompt": "Tools to check reviews?",
      "options": [
        "None",
        "Fakespot / ReviewMeta",
        "Google",
        "Ask seller"
      ],
      "correct": 1,
      "explanation": "These tools analyze patterns to detect bots."
    },
    {
      "type": 1,
      "prompt": "Why do they do it?",
      "options": [
        "Ego",
        "To rank higher in search results and sell junk",
        "Fun",
        "Help"
      ],
      "correct": 1,
      "explanation": "Higher ratings = Top of search = More sales."
    },
    {
      "type": 2,
      "prompt": "You receive a package from Amazon you didn't order (seeds, cheap toy).",
      "options": [
        "Gift",
        "Brushing Scam",
        "Mistake",
        "Santa"
      ],
      "correct": 1,
      "explanation": "Sellers send cheap items to real addresses so they can write a 'Verified Purchase' review in your name."
    },
    {
      "type": 2,
      "prompt": "Is Brushing dangerous?",
      "options": [
        "No, free stuff",
        "Yes, it means your name/address is leaked to scammers.",
        "Maybe",
        "Fun"
      ],
      "correct": 1,
      "explanation": "It confirms your data is compromised."
    },
    {
      "type": 2,
      "prompt": "Should you plant the mystery seeds?",
      "options": [
        "Yes",
        "NO. They could be invasive species or carrying pests.",
        "Maybe",
        "Eat them"
      ],
      "correct": 1,
      "explanation": "Biosecurity risk. Report to Department of Agriculture."
    },
    {
      "type": 2,
      "prompt": "Can they charge you for it?",
      "options": [
        "No",
        "Usually no, as they need it to look like a gift/sale",
        "Yes",
        "Maybe"
      ],
      "correct": 1,
      "explanation": "They pay for the item themselves to generate the review."
    },
    {
      "type": 2,
      "prompt": "What should you do with the item?",
      "options": [
        "Keep/Bin it",
        "Change your passwords on shopping sites",
        "Return it",
        "Sell it"
      ],
      "correct": 1,
      "explanation": "Secure your accounts as your data is out there."
    },
    {
      "type": 2,
      "prompt": "Why verify the purchase?",
      "options": [
        "Rules",
        "Verified reviews carry more weight in search algorithms",
        "Truth",
        "Nice"
      ],
      "correct": 1,
      "explanation": "Platforms trust reviews from confirmed deliveries more."
    },
    {
      "type": 2,
      "prompt": "Does this happen on eBay?",
      "options": [
        "Yes",
        "Mostly Amazon/AliExpress",
        "No",
        "Rarely"
      ],
      "correct": 1,
      "explanation": "It targets platforms that require proof of shipping for reviews."
    },
    {
      "type": 2,
      "prompt": "You see a review under your name you didn't write.",
      "options": [
        "Glitch",
        "Identity theft / Account takeover",
        "Ghost",
        "Forget"
      ],
      "correct": 1,
      "explanation": "Report it to the platform immediately."
    },
    {
      "type": 2,
      "prompt": "Is it illegal?",
      "options": [
        "Yes",
        "No",
        "Maybe",
        "Sort of"
      ],
      "correct": 0,
      "explanation": "It is fraud and often involves mail fraud laws."
    },
    {
      "type": 2,
      "prompt": "The return address is fake.",
      "options": [
        "Standard",
        "Prevents returns",
        "Smart",
        "Okay"
      ],
      "correct": 1,
      "explanation": "They don't want the item back."
    },
    {
      "type": 3,
      "prompt": "A card in the box says: 'Get a $20 gift card for a 5-star review'.",
      "options": [
        "Do it",
        "Illegal/Against T&Cs. This biases the rating system.",
        "Ignore",
        "Report"
      ],
      "correct": 1,
      "explanation": "Buying reviews is banned on major platforms and often illegal under consumer law."
    },
    {
      "type": 3,
      "prompt": "A Facebook group offers 'Free Products' in exchange for reviews.",
      "options": [
        "Join",
        "Review Manipulation scam",
        "Good deal",
        "Work"
      ],
      "correct": 1,
      "explanation": "These groups coordinate fake reviews to boost product rankings."
    },
    {
      "type": 3,
      "prompt": "They refund you via PayPal AFTER you post the review.",
      "options": [
        "Smart",
        "This hides the refund from Amazon's detection systems",
        "Safe",
        "Okay"
      ],
      "correct": 1,
      "explanation": "Taking the transaction off-platform hides the bribe."
    },
    {
      "type": 3,
      "prompt": "Does the ACCC punish this?",
      "options": [
        "Yes",
        "No",
        "Maybe",
        "Sometimes"
      ],
      "correct": 0,
      "explanation": "Misleading consumers with fake testimonials attracts huge fines."
    },
    {
      "type": 3,
      "prompt": "Can you trust 'Influencer' reviews?",
      "options": [
        "Always",
        "Only if they disclose '#Ad' or sponsorship",
        "Never",
        "Usually"
      ],
      "correct": 1,
      "explanation": "Undisclosed sponsorship is misleading conduct."
    },
    {
      "type": 3,
      "prompt": "The seller harasses you to delete a negative review.",
      "options": [
        "Delete it",
        "Report harassment to the platform",
        "Ignore",
        "Block"
      ],
      "correct": 1,
      "explanation": "Sellers try to bully customers into removing honest feedback."
    },
    {
      "type": 3,
      "prompt": "They offer a full refund if you change 1 star to 5 stars.",
      "options": [
        "Change it",
        "Don't. That helps them scam the next person.",
        "Take money",
        "Nice"
      ],
      "correct": 1,
      "explanation": "Protect the community by keeping your honest review up."
    },
    {
      "type": 3,
      "prompt": "What is 'Review Gating'?",
      "options": [
        "Fences",
        "Asking customers if they are happy FIRST, and only inviting happy ones to review",
        "Gates",
        "Lock"
      ],
      "correct": 1,
      "explanation": "Filtering out unhappiness distorts the truth."
    },
    {
      "type": 3,
      "prompt": "Are video reviews always real?",
      "options": [
        "Yes",
        "No, actors are paid on Fiverr to make fake video testimonials",
        "Usually",
        "Maybe"
      ],
      "correct": 1,
      "explanation": "You can buy a 'satisfied customer' video for $5."
    },
    {
      "type": 3,
      "prompt": "Trustpilot warning badges.",
      "options": [
        "Ignore",
        "Take seriously. It means they detected fraud.",
        "Glitch",
        "Decor"
      ],
      "correct": 1,
      "explanation": "Platforms flag businesses caught cheating."
    },
    {
      "type": 4,
      "prompt": "A restaurant gets fifty 1-star reviews in one hour.",
      "options": [
        "Bad food",
        "Review bombing attack",
        "Bad luck",
        "Busy"
      ],
      "correct": 1,
      "explanation": "Competitors or trolls organize attacks to destroy ratings."
    },
    {
      "type": 4,
      "prompt": "The review makes false claims (e.g., 'Found a rat') without proof.",
      "options": [
        "Believe",
        "Suspicious. Used to cause maximum damage.",
        "Scary",
        "Avoid"
      ],
      "correct": 1,
      "explanation": "Extreme claims scare customers away effectively."
    },
    {
      "type": 4,
      "prompt": "They demand money to remove the bad reviews.",
      "options": [
        "Pay",
        "Extortion scam",
        "Negotiate",
        "Ignore"
      ],
      "correct": 1,
      "explanation": "Scammers post bad reviews then offer 'Reputation Management' services to remove them."
    },
    {
      "type": 4,
      "prompt": "The reviewer recommends a SPECIFIC competitor in their review.",
      "options": [
        "Helpful",
        "Marketing tactic/Sabotage",
        "Nice",
        "Tip"
      ],
      "correct": 1,
      "explanation": "Steering traffic to another business is a clear sign of sabotage."
    },
    {
      "type": 4,
      "prompt": "Does Google remove these?",
      "options": [
        "Automatically",
        "Only if reported and proven to violate policy (Hard)",
        "Always",
        "Never"
      ],
      "correct": 1,
      "explanation": "Getting fake reviews removed is a slow, difficult process."
    },
    {
      "type": 4,
      "prompt": "A brand new account leaves a 1-star review with no text.",
      "options": [
        "Shy",
        "Bot/Fake",
        "Angry",
        "Lazy"
      ],
      "correct": 1,
      "explanation": "Star-only ratings lower the average without leaving evidence to dispute."
    },
    {
      "type": 4,
      "prompt": "Crowdsourced sabotage (e.g., Reddit/TikTok army).",
      "options": [
        "Justice",
        "Mob mentality/Brigading",
        "Fun",
        "Fair"
      ],
      "correct": 1,
      "explanation": "Internet mobs can destroy businesses over unverified rumors."
    },
    {
      "type": 4,
      "prompt": "How to spot a real bad review?",
      "options": [
        "Specific details",
        "Reasonable tone",
        "Photos of issue",
        "All of above"
      ],
      "correct": 3,
      "explanation": "Real complaints usually have substance and nuance."
    },
    {
      "type": 4,
      "prompt": "The business owner replies professionally with facts.",
      "options": [
        "Defensive",
        "Good sign. Shows they care and have records.",
        "Rude",
        "Mean"
      ],
      "correct": 1,
      "explanation": "Look at how the owner handles the complaint."
    },
    {
      "type": 4,
      "prompt": "Is it illegal to fake bad reviews?",
      "options": [
        "No",
        "Yes, defamation and anti-competitive conduct",
        "Maybe",
        "Online is free"
      ],
      "correct": 1,
      "explanation": "You can be sued for defamation."
    },
    {
      "type": 5,
      "prompt": "A crypto site has video testimonials of people earning millions.",
      "options": [
        "Must be real",
        "Paid actors. Very common in crypto scams.",
        "Join",
        "Invest"
      ],
      "correct": 1,
      "explanation": "These are often Fiverr actors reading a script."
    },
    {
      "type": 5,
      "prompt": "The 'Doctor' endorsing the pill is wearing a lab coat but has no name badge.",
      "options": [
        "Privacy",
        "Fake doctor (Stock photo model)",
        "Real",
        "Expert"
      ],
      "correct": 1,
      "explanation": "Stock photos of doctors are used to sell snake oil."
    },
    {
      "type": 5,
      "prompt": "The testimonials are all dated 'Today'.",
      "options": [
        "Busy day",
        "Script that auto-updates dates",
        "Viral",
        "Active"
      ],
      "correct": 1,
      "explanation": "Dynamic scripts change the date to always look fresh."
    },
    {
      "type": 5,
      "prompt": "Reverse image search the 'Success Story' photo.",
      "options": [
        "Stalking",
        "Verification. Usually shows the photo is a stock image.",
        "Hard",
        "Why"
      ],
      "correct": 1,
      "explanation": "The 'successful investor' is usually a model from a photo library."
    },
    {
      "type": 5,
      "prompt": "Before/After photos look Photoshopped.",
      "options": [
        "Diet worked",
        "Fake. Lighting/Editing used to mislead.",
        "Real",
        "Good"
      ],
      "correct": 1,
      "explanation": "Weight loss/skincare scams rely on edited photos."
    },
    {
      "type": 5,
      "prompt": "They quote 'Celebrities' who endorsed it.",
      "options": [
        "Impressive",
        "Lie. Celebs sue for this constantly.",
        "Cool",
        "Trust"
      ],
      "correct": 1,
      "explanation": "Fake news articles claim celebs use the product without permission."
    },
    {
      "type": 5,
      "prompt": "The testimonials are unverified screenshots of text messages.",
      "options": [
        "Proof",
        "Easy to fake (Text yourself)",
        "Real",
        "Social"
      ],
      "correct": 1,
      "explanation": "Screenshots of chats are not proof."
    },
    {
      "type": 5,
      "prompt": "No negative reviews exist anywhere.",
      "options": [
        "Perfect product",
        "Censorship. They delete everything bad.",
        "Amazing",
        "Buy"
      ],
      "correct": 1,
      "explanation": "Nothing is perfect. Zero complaints is suspicious."
    },
    {
      "type": 5,
      "prompt": "The 'News' logos (CNN, BBC) are on the site.",
      "options": [
        "Featured",
        "Fake 'As Seen On' banner",
        "Real",
        "News"
      ],
      "correct": 1,
      "explanation": "Sticking a logo on a website doesn't mean they were featured."
    },
    {
      "type": 5,
      "prompt": "Impact?",
      "options": [
        "None",
        "Financial ruin or health issues",
        "Annoying",
        "Fun"
      ],
      "correct": 1,
      "explanation": "Believing fake medical/financial reviews is dangerous."
    }
  ]
};