export default [
  {
    id: "39-01",
    title: "Spotting Bot Reviews",
    description: "When the 'people' aren't real.",
    questions: [
      {
        question: "A product has 5,000 reviews, all 5 stars, posted in the last 3 days.",
        options: ["Popular product", "Bot attack. Natural reviews accumulate over time.", "Viral", "Good marketing"],
        correctAnswer: 1,
        explanation: "A sudden spike in perfect reviews is the clearest sign of a bought bot campaign."
      },
      {
        question: "The reviews use generic phrases like 'Good item', 'Fast ship', 'Nice'.",
        options: ["Succinct", "Bot filler text. Real humans describe specific features.", "Lazy", "Efficient"],
        correctAnswer: 1,
        explanation: "Bots use vague language that could apply to any product."
      },
      {
        question: "The user names are random letters/numbers (e.g., 'User129384').",
        options: ["Privacy", "Bot accounts generated by scripts.", "New", "Standard"],
        correctAnswer: 1,
        explanation: "Real users usually have names or customizable handles."
      },
      {
        question: "The review mentions a different product (e.g., review for headphones on a toaster page).",
        options: ["Glitch", "Review Hijacking. The seller swapped the product page to keep old 5-star ratings.", "Mistake", "Confusion"],
        correctAnswer: 1,
        explanation: "Sellers reuse old pages with high ratings for new junk products."
      },
      {
        question: "A graph of reviews shows only 5-star and 1-star ratings (C-shape).",
        options: ["Polarizing product", "Manipulation. Paid 5-stars vs Real angry 1-stars.", "Okay", "Normal"],
        correctAnswer: 1,
        explanation: "Real products usually have a bell curve (mostly 3-4 stars)."
      },
      {
        question: "The English is broken or unnatural across hundreds of reviews.",
        options: ["Global buyers", "Click farm content.", "Translation", "Fine"],
        correctAnswer: 1,
        explanation: "Click farms often use poor translation software."
      },
      {
        question: "All the reviewers have only reviewed this one single item.",
        options: ["Loyal", "Fake accounts created solely for this scam.", "New", "Fan"],
        correctAnswer: 1,
        explanation: "Real shoppers have a history of diverse purchases."
      },
      {
        question: "Can you trust 'Amazon's Choice' blindly?",
        options: ["Yes", "No, it's an algorithm based on sales volume (which can be faked)", "Always", "Maybe"],
        correctAnswer: 1,
        explanation: "The badge is algorithmic, not a quality guarantee."
      },
      {
        question: "Tools to check reviews?",
        options: ["None", "Fakespot / ReviewMeta", "Google", "Ask seller"],
        correctAnswer: 1,
        explanation: "These tools analyze patterns to detect bots."
      },
      {
        question: "Why do they do it?",
        options: ["Ego", "To rank higher in search results and sell junk", "Fun", "Help"],
        correctAnswer: 1,
        explanation: "Higher ratings = Top of search = More sales."
      }
    ]
  },
  {
    id: "39-02",
    title: "Brushing Scams",
    description: "Why did I get a random package?",
    questions: [
      {
        question: "You receive a package from Amazon you didn't order (seeds, cheap toy).",
        options: ["Gift", "Brushing Scam", "Mistake", "Santa"],
        correctAnswer: 1,
        explanation: "Sellers send cheap items to real addresses so they can write a 'Verified Purchase' review in your name."
      },
      {
        question: "Is Brushing dangerous?",
        options: ["No, free stuff", "Yes, it means your name/address is leaked to scammers.", "Maybe", "Fun"],
        correctAnswer: 1,
        explanation: "It confirms your data is compromised."
      },
      {
        question: "Should you plant the mystery seeds?",
        options: ["Yes", "NO. They could be invasive species or carrying pests.", "Maybe", "Eat them"],
        correctAnswer: 1,
        explanation: "Biosecurity risk. Report to Department of Agriculture."
      },
      {
        question: "Can they charge you for it?",
        options: ["No", "Usually no, as they need it to look like a gift/sale", "Yes", "Maybe"],
        correctAnswer: 1,
        explanation: "They pay for the item themselves to generate the review."
      },
      {
        question: "What should you do with the item?",
        options: ["Keep/Bin it", "Change your passwords on shopping sites", "Return it", "Sell it"],
        correctAnswer: 1,
        explanation: "Secure your accounts as your data is out there."
      },
      {
        question: "Why verify the purchase?",
        options: ["Rules", "Verified reviews carry more weight in search algorithms", "Truth", "Nice"],
        correctAnswer: 1,
        explanation: "Platforms trust reviews from confirmed deliveries more."
      },
      {
        question: "Does this happen on eBay?",
        options: ["Yes", "Mostly Amazon/AliExpress", "No", "Rarely"],
        correctAnswer: 1,
        explanation: "It targets platforms that require proof of shipping for reviews."
      },
      {
        question: "You see a review under your name you didn't write.",
        options: ["Glitch", "Identity theft / Account takeover", "Ghost", "Forget"],
        correctAnswer: 1,
        explanation: "Report it to the platform immediately."
      },
      {
        question: "Is it illegal?",
        options: ["Yes", "No", "Maybe", "Sort of"],
        correctAnswer: 0,
        explanation: "It is fraud and often involves mail fraud laws."
      },
      {
        question: "The return address is fake.",
        options: ["Standard", "Prevents returns", "Smart", "Okay"],
        correctAnswer: 1,
        explanation: "They don't want the item back."
      }
    ]
  },
  {
    id: "39-03",
    title: "Incentivized Reviews",
    description: "Buying your opinion.",
    questions: [
      {
        question: "A card in the box says: 'Get a $20 gift card for a 5-star review'.",
        options: ["Do it", "Illegal/Against T&Cs. This biases the rating system.", "Ignore", "Report"],
        correctAnswer: 1,
        explanation: "Buying reviews is banned on major platforms and often illegal under consumer law."
      },
      {
        question: "A Facebook group offers 'Free Products' in exchange for reviews.",
        options: ["Join", "Review Manipulation scam", "Good deal", "Work"],
        correctAnswer: 1,
        explanation: "These groups coordinate fake reviews to boost product rankings."
      },
      {
        question: "They refund you via PayPal AFTER you post the review.",
        options: ["Smart", "This hides the refund from Amazon's detection systems", "Safe", "Okay"],
        correctAnswer: 1,
        explanation: "Taking the transaction off-platform hides the bribe."
      },
      {
        question: "Does the ACCC punish this?",
        options: ["Yes", "No", "Maybe", "Sometimes"],
        correctAnswer: 0,
        explanation: "Misleading consumers with fake testimonials attracts huge fines."
      },
      {
        question: "Can you trust 'Influencer' reviews?",
        options: ["Always", "Only if they disclose '#Ad' or sponsorship", "Never", "Usually"],
        correctAnswer: 1,
        explanation: "Undisclosed sponsorship is misleading conduct."
      },
      {
        question: "The seller harasses you to delete a negative review.",
        options: ["Delete it", "Report harassment to the platform", "Ignore", "Block"],
        correctAnswer: 1,
        explanation: "Sellers try to bully customers into removing honest feedback."
      },
      {
        question: "They offer a full refund if you change 1 star to 5 stars.",
        options: ["Change it", "Don't. That helps them scam the next person.", "Take money", "Nice"],
        correctAnswer: 1,
        explanation: "Protect the community by keeping your honest review up."
      },
      {
        question: "What is 'Review Gating'?",
        options: ["Fences", "Asking customers if they are happy FIRST, and only inviting happy ones to review", "Gates", "Lock"],
        correctAnswer: 1,
        explanation: "Filtering out unhappiness distorts the truth."
      },
      {
        question: "Are video reviews always real?",
        options: ["Yes", "No, actors are paid on Fiverr to make fake video testimonials", "Usually", "Maybe"],
        correctAnswer: 1,
        explanation: "You can buy a 'satisfied customer' video for $5."
      },
      {
        question: "Trustpilot warning badges.",
        options: ["Ignore", "Take seriously. It means they detected fraud.", "Glitch", "Decor"],
        correctAnswer: 1,
        explanation: "Platforms flag businesses caught cheating."
      }
    ]
  },
  {
    id: "39-04",
    title: "Competitor Sabotage",
    description: "Weaponizing the 1-star rating.",
    questions: [
      {
        question: "A restaurant gets fifty 1-star reviews in one hour.",
        options: ["Bad food", "Review bombing attack", "Bad luck", "Busy"],
        correctAnswer: 1,
        explanation: "Competitors or trolls organize attacks to destroy ratings."
      },
      {
        question: "The review makes false claims (e.g., 'Found a rat') without proof.",
        options: ["Believe", "Suspicious. Used to cause maximum damage.", "Scary", "Avoid"],
        correctAnswer: 1,
        explanation: "Extreme claims scare customers away effectively."
      },
      {
        question: "They demand money to remove the bad reviews.",
        options: ["Pay", "Extortion scam", "Negotiate", "Ignore"],
        correctAnswer: 1,
        explanation: "Scammers post bad reviews then offer 'Reputation Management' services to remove them."
      },
      {
        question: "The reviewer recommends a SPECIFIC competitor in their review.",
        options: ["Helpful", "Marketing tactic/Sabotage", "Nice", "Tip"],
        correctAnswer: 1,
        explanation: "Steering traffic to another business is a clear sign of sabotage."
      },
      {
        question: "Does Google remove these?",
        options: ["Automatically", "Only if reported and proven to violate policy (Hard)", "Always", "Never"],
        correctAnswer: 1,
        explanation: "Getting fake reviews removed is a slow, difficult process."
      },
      {
        question: "A brand new account leaves a 1-star review with no text.",
        options: ["Shy", "Bot/Fake", "Angry", "Lazy"],
        correctAnswer: 1,
        explanation: "Star-only ratings lower the average without leaving evidence to dispute."
      },
      {
        question: "Crowdsourced sabotage (e.g., Reddit/TikTok army).",
        options: ["Justice", "Mob mentality/Brigading", "Fun", "Fair"],
        correctAnswer: 1,
        explanation: "Internet mobs can destroy businesses over unverified rumors."
      },
      {
        question: "How to spot a real bad review?",
        options: ["Specific details", "Reasonable tone", "Photos of issue", "All of above"],
        correctAnswer: 3,
        explanation: "Real complaints usually have substance and nuance."
      },
      {
        question: "The business owner replies professionally with facts.",
        options: ["Defensive", "Good sign. Shows they care and have records.", "Rude", "Mean"],
        correctAnswer: 1,
        explanation: "Look at how the owner handles the complaint."
      },
      {
        question: "Is it illegal to fake bad reviews?",
        options: ["No", "Yes, defamation and anti-competitive conduct", "Maybe", "Online is free"],
        correctAnswer: 1,
        explanation: "You can be sued for defamation."
      }
    ]
  },
  {
    id: "39-05",
    title: "Testimonial Scams (Investment/Medical)",
    description: "Lies that cost you your life savings or health.",
    questions: [
      {
        question: "A crypto site has video testimonials of people earning millions.",
        options: ["Must be real", "Paid actors. Very common in crypto scams.", "Join", "Invest"],
        correctAnswer: 1,
        explanation: "These are often Fiverr actors reading a script."
      },
      {
        question: "The 'Doctor' endorsing the pill is wearing a lab coat but has no name badge.",
        options: ["Privacy", "Fake doctor (Stock photo model)", "Real", "Expert"],
        correctAnswer: 1,
        explanation: "Stock photos of doctors are used to sell snake oil."
      },
      {
        question: "The testimonials are all dated 'Today'.",
        options: ["Busy day", "Script that auto-updates dates", "Viral", "Active"],
        correctAnswer: 1,
        explanation: "Dynamic scripts change the date to always look fresh."
      },
      {
        question: "Reverse image search the 'Success Story' photo.",
        options: ["Stalking", "Verification. Usually shows the photo is a stock image.", "Hard", "Why"],
        correctAnswer: 1,
        explanation: "The 'successful investor' is usually a model from a photo library."
      },
      {
        question: "Before/After photos look Photoshopped.",
        options: ["Diet worked", "Fake. Lighting/Editing used to mislead.", "Real", "Good"],
        correctAnswer: 1,
        explanation: "Weight loss/skincare scams rely on edited photos."
      },
      {
        question: "They quote 'Celebrities' who endorsed it.",
        options: ["Impressive", "Lie. Celebs sue for this constantly.", "Cool", "Trust"],
        correctAnswer: 1,
        explanation: "Fake news articles claim celebs use the product without permission."
      },
      {
        question: "The testimonials are unverified screenshots of text messages.",
        options: ["Proof", "Easy to fake (Text yourself)", "Real", "Social"],
        correctAnswer: 1,
        explanation: "Screenshots of chats are not proof."
      },
      {
        question: "No negative reviews exist anywhere.",
        options: ["Perfect product", "Censorship. They delete everything bad.", "Amazing", "Buy"],
        correctAnswer: 1,
        explanation: "Nothing is perfect. Zero complaints is suspicious."
      },
      {
        question: "The 'News' logos (CNN, BBC) are on the site.",
        options: ["Featured", "Fake 'As Seen On' banner", "Real", "News"],
        correctAnswer: 1,
        explanation: "Sticking a logo on a website doesn't mean they were featured."
      },
      {
        question: "Impact?",
        options: ["None", "Financial ruin or health issues", "Annoying", "Fun"],
        correctAnswer: 1,
        explanation: "Believing fake medical/financial reviews is dangerous."
      }
    ]
  }
];